server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/system2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false

  # Redis配置
  data:
    redis:
      host: 192.168.80.128
      port: 6379
      database: 0
      password:
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

  # Activiti配置
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
    deployment-mode: never-fail
    process-definition-location-prefix: classpath:/processes/
    async-executor-activate: false
    mail-server-use-ssl: true
    font:
      activity-font-name: 宋体
      label-font-name: 宋体
      annotation-font-name: 宋体
    deployment-resources-pattern:
      - classpath*:/processes/*.*
      - classpath*:/processes/*/*.*
    rest-api-enabled: true
    rest-api-mapping: /activiti-rest/*
    rest-api-servlet-name: activiti-rest
    modeler:
      enabled: true
      context-path: /modeler
    security:
      enabled: false

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.project.system2.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.project.system2.config.typehandler
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# Token配置
token:
  header: Authorization
  secret: your-secret-key
  expiration: 86400

# 日志配置
logging:
  level:
    com.project.system2: debug
    org.springframework: warn