server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: password
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.project.system2.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.project.system2.config.typehandler
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

token:
  header: Authorization
  secret: your-secret-key
  expiration: 86400

logging:
  level:
    com.project.system2: debug
    org.springframework: warn

# Activiti 配置
spring:
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
    deployment-mode: never-fail
    process-definition-location-prefix: classpath:/processes/
    async-executor-activate: false
    mail-server-use-ssl: true
    font:
      activity-font-name: 宋体
      label-font-name: 宋体
      annotation-font-name: 宋体
    deployment-resources-pattern:
      - classpath*:/processes/*.*
      - classpath*:/processes/*/*.*
    rest-api-enabled: true
    rest-api-mapping: /activiti-rest/*
    rest-api-servlet-name: activiti-rest
    modeler:
      enabled: true
      context-path: /modeler
    security:
      enabled: false

# Redis配置
spring:
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms