server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/system2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false

  # Redis配置
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 192.168.80.128
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: 
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0

  # Activiti配置
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
    deployment-mode: never-fail
    process-definition-location-prefix: classpath:/processes/
    async-executor-activate: false
    mail-server-use-ssl: true
    font:
      activity-font-name: 宋体
      label-font-name: 宋体
      annotation-font-name: 宋体
    deployment-resources-pattern:
      - classpath*:/processes/*.*
      - classpath*:/processes/*/*.*
    rest-api-enabled: true
    rest-api-mapping: /activiti-rest/*
    rest-api-servlet-name: activiti-rest
    modeler:
      enabled: true
      context-path: /modeler
    security:
      enabled: false
      # 不需要认证的路径
      ignored:
        urls:
          - /auth/login
          - /auth/register
          - /auth/captcha
          - /profile/**
          - /common/download**
          - /common/download/resource**
          - /swagger-ui.html
          - /swagger-resources/**
          - /webjars/**
          - /*/api-docs
          - /druid/**
          - /actuator/**
          - /
          - /*.html
          - /**/*.html
          - /**/*.css
          - /**/*.js
          - /profile/**
          - /avatar/**
          - /file/**

# MyBatis-Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.project.system2.domain.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

# Token配置
token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30

# JWT配置
jwt:
  # 令牌密钥
  secret: jdsadsajoincxznsajdsajoincxznsajdsajoincxzns
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # 令牌前缀
  tokenPrefix: "Bearer "
  # 令牌头部
  header: Authorization

# 日志配置
logging:
  level:
    com.project.system2: debug
    org.springframework: warn